# Generated by Django 6.0.7 on 2026-09-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ospite',
            fields=[
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=15)),
                ('e_mail', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('documentoidentita', models.CharField(db_column='documentoIdentita', max_length=9, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'OSPITE',
            },
        ),
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=15)),
                ('e_mail', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('documentoidentita', models.CharField(db_column='documentoIdentita', max_length=9, primary_key=True, serialize=False)),
                ('ruolo', models.CharField(max_length=25)),
                ('attivo', models.BooleanField()),
            ],
            options={
                'db_table': 'PERSONALE',
            },
        ),
        migrations.CreateModel(
            name='ServizioAggiuntivo',
            fields=[
                ('nome', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descrizione', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attivo', models.BooleanField()),
            ],
            options={
                'db_table': 'SERVIZIO_AGGIUNTIVO',
            },
        ),
        migrations.CreateModel(
            name='Stagione',
            fields=[
                ('nome', models.CharField(max_length=20)),
                ('moltiplicatore', models.DecimalField(decimal_places=2, max_digits=3)),
                ('datainizio', models.DateField(db_column='dataInizio', primary_key=True, serialize=False)),
                ('datafine', models.DateField(db_column='dataFine')),
            ],
            options={
                'db_table': 'STAGIONE',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('pk', models.CompositePrimaryKey('piano', 'numerocamera', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tipologia', models.CharField(max_length=15)),
                ('numeromassimoospiti', models.DecimalField(db_column='numeroMassimoOspiti', decimal_places=0, max_digits=2)),
                ('piano', models.DecimalField(decimal_places=0, max_digits=2)),
                ('descrizione', models.CharField(max_length=200)),
                ('stato', models.CharField(max_length=12)),
                ('prezzobasenotte', models.DecimalField(db_column='prezzoBaseNotte', decimal_places=2, max_digits=8)),
                ('numerocamera', models.DecimalField(db_column='numeroCamera', decimal_places=0, max_digits=3)),
                ('attivo', models.BooleanField()),
            ],
            options={
                'db_table': 'CAMERA',
                'unique_together': {('piano', 'numerocamera')},
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('codiceprenotazione', models.DecimalField(db_column='codicePrenotazione', decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('dataarrivo', models.DateField(db_column='dataArrivo')),
                ('datapartenza', models.DateField(db_column='dataPartenza')),
                ('numeroospiti', models.DecimalField(db_column='numeroOspiti', decimal_places=0, max_digits=2)),
                ('stato', models.CharField(max_length=12)),
                ('datacheckineffettivo', models.DateField(blank=True, db_column='dataCheckInEffettivo', null=True)),
                ('piano', models.DecimalField(decimal_places=0, max_digits=2)),
                ('numerocamera', models.DecimalField(db_column='numeroCamera', decimal_places=0, max_digits=3)),
                ('camera', models.ForeignObject(from_fields=('piano', 'numerocamera'), on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.camera', to_fields=('piano', 'numerocamera'))),
                ('documentoidentitaospite', models.ForeignKey(db_column='documentoIdentitaOspite', on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.ospite')),
                ('datainiziostagione', models.ForeignKey(blank=True, db_column='dataInizioStagione', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.stagione')),
            ],
            options={
                'db_table': 'PRENOTAZIONE',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('codicepagamento', models.DecimalField(db_column='codicePagamento', decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('importototale', models.DecimalField(db_column='importoTotale', decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('codiceprenotazione', models.OneToOneField(db_column='codicePrenotazione', on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.prenotazione')),
            ],
            options={
                'db_table': 'PAGAMENTO',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('codicerecensione', models.DecimalField(db_column='codiceRecensione', decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('voto', models.DecimalField(decimal_places=0, max_digits=2)),
                ('commento', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.DateField()),
                ('codiceprenotazione', models.OneToOneField(db_column='codicePrenotazione', on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.prenotazione')),
            ],
            options={
                'db_table': 'RECENSIONE',
            },
        ),
        migrations.CreateModel(
            name='Occupante',
            fields=[
                ('pk', models.CompositePrimaryKey('codiceprenotazione', 'documentoidentita', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('documentoidentita', models.CharField(db_column='documentoIdentita', max_length=9)),
                ('codiceprenotazione', models.ForeignKey(db_column='codicePrenotazione', on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.prenotazione')),
            ],
            options={
                'db_table': 'OCCUPANTE',
                'unique_together': {('codiceprenotazione', 'documentoidentita')},
            },
        ),
        migrations.CreateModel(
            name='Pulizia',
            fields=[
                ('pk', models.CompositePrimaryKey('piano', 'numerocamera', 'data', blank=True, editable=False, primary_key=True, serialize=False)),
                ('piano', models.DecimalField(decimal_places=0, max_digits=2)),
                ('numerocamera', models.DecimalField(db_column='numeroCamera', decimal_places=0, max_digits=3)),
                ('data', models.DateField()),
                ('camera', models.ForeignObject(from_fields=('piano', 'numerocamera'), on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.camera', to_fields=('piano', 'numerocamera'))),
                ('documentoidentitaaddetto', models.ForeignKey(db_column='documentoIdentitaAddetto', on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.personale')),
            ],
            options={
                'db_table': 'PULIZIA',
                'unique_together': {('piano', 'numerocamera', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('pk', models.CompositePrimaryKey('codiceprenotazione', 'nomeservizio', blank=True, editable=False, primary_key=True, serialize=False)),
                ('codiceprenotazione', models.ForeignKey(db_column='codicePrenotazione', on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.prenotazione')),
                ('nomeservizio', models.ForeignKey(db_column='nomeServizio', on_delete=django.db.models.deletion.DO_NOTHING, to='BedAndBreakfast.servizioaggiuntivo')),
            ],
            options={
                'db_table': 'INCLUDE',
                'unique_together': {('codiceprenotazione', 'nomeservizio')},
            },
        ),
    ]
